#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=$SOURCE_COMMIT --build-arg DATASET=thesimpsons -t $DOCKER_REPO:thesimpsons .
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=$SOURCE_COMMIT --build-arg DATASET=thehightable -t $DOCKER_REPO:thehightable .

echo "------ HOOK END - BUILD -------"
